Streamers-Workshop/Blazebot

plugins/so.js

added a shoutout plugin so ppl could do something like !so ssrjazz to shoutout fellow streamers in their chat. (I use ! as my prefix for TrovoBot commands)

Adding a shoutout (so) plugin file to new_branch

---

plugins/stats.README.md
plugins/stats.Settings.json
plugins/stats.js

Take # 2 Warzone stats plugin.

warzone stats plugin

---

bat/install.bat
bat/startup.bat
bat/update.bat

make it easier for people to install and launch bot

Create: bat files for install & startup

---

plugins/raid.js

Raid command.
Sends a message 5 times with the name and the url of the target channel. (1 message/second)
Example: !raid username
Usable by mods and the creator of the channel.

Raid command

---

.env
index.js
package-lock.json
plugins/toggleSource.js
plugins/uptime.js

Added a plugin to allow toggling on/off visibility of sources.
Also added the "obs" argument to the plugins functionality.

Toggle obs sources plugin.

---

plugins/so.js

Added check if username starts with "@" character and outputs shoutout to chat depending on result.

Updated SO to work with and without @ character

---

index.js

Self-explanatory :D
I changed the if-statement quite a bit though. I assume that the permissions-array in the plugins mean "the sender needs to have any of these roles".

Fixed wrongly placed braces

---

plugins/say.js

Say Command | Writes a message by the bot
Usage: (Prefix)clear (text)

Say Command

---

plugins/valorant-stats.js

Usage is changed !valorant-stats Nickname#TAG

Plugin Update: Valorant Stats, Now can see other players stats

---

plugins/say.js

Correct format | Say.js

---

chatmessagefilters/swears_and_links.js
index.js
plugins/create.js
plugins/obs-text-test.js
plugins/ping.js
plugins/pong.js
plugins/raid.js
plugins/so.js
plugins/text-overlay-test.js
plugins/toggleSource.js
plugins/uptime.js
plugins/valorant-stats.js
plugins/warzone-stats.js

Just way more elegant than before.

Dynamically display loaded plugins, events and chat filters

---

README-es.md

Documentation translation to Spanish language.

Create: fully updated README-es.md

---

plugins/create/README.md
plugins/create/create.js

rehkloos -> create folder for plugin javascript file
rehkloos -> fix some eslint Caramel Case issues
todo: needs a way to run command without needing to reboot bot

Plug-in: create command

---

README.md

Include direct link to the file with the Spanish Translation.

Include link to Spanish Translation in the principal README.md

---

plugins/command-list/README.md
plugins/command-list/command-list.js

- Need spacing and a "," between each command in the array
- connect to plugin module so it only list files that are present

Plug-in: command-list

---

plugins/delete/README.md
plugins/delete/delete.js

Plug-in: Delete commands

---

modules/Services.js
plugins/create/create.js
plugins/redeem/README.md
plugins/redeem/redeem.js
plugins/redeem/redeem.json

Fixed some eslint warnings & a minor bug in Services

Added redeem and minor fixes

---

package-lock.json
package.json
plugins/giveaway/README.md
plugins/giveaway/giveaway.js
plugins/join/README.md
plugins/join/join.js
services/obs/obs.json

join command is used to join a giveaway if one is active.

Giveaway & join command

---

package-lock.json
package.json
plugins/create/create.js
plugins/delete/delete.js
plugins/edit/README.md
plugins/edit/edit.js
plugins/test/test.js

-Added userCreated to for commands created by !Create
-Changed delete so it can only remove commands created with !Create
-Made edit to edit commands created with !Create. Only these ones can be edited with this command.

Added edit command

---

plugins/hydrate/README.md
plugins/hydrate/hydrate.js
plugins/hydrate/hydrate.json

hydrate: add ability to set reminder time (in minutes)

---

plugins/alert-follow/alert-follow.js
plugins/alert-spell/alert-spell.json
plugins/alert-sub/alert-sub.js
plugins/alert-sub/alert-sub.json
settings.json

Fixed a few things in alerts and added full http's

---

package-lock.json
package.json
plugins/google/README.md
plugins/google/google.js
plugins/google/google.json

Plug-in: Google search

---

localization/en.json
plugins/google/README.md
plugins/google/google.js
plugins/google/google.json
plugins/instagram/README.md
plugins/instagram/instagram.js
plugins/instagram/instagram.json
plugins/random-game/README.md
plugins/random-game/game-list.txt
plugins/random-game/random-game.js
plugins/random-game/random-game.json

Plug-in (2.0.0): Latest Instagram post
Plug-in (2.0.0): Random game picker
Plug-in (2.0.0): Google search

Plug-ins Update (2.0.0): rewrite Google, Game Picker & Add IG

---

localization/en.json
modules/Tool.js
plugins/hydrate/README.md
plugins/hydrate/hydrate.js
plugins/hydrate/hydrate.json
plugins/instagram/instagram.js
plugins/urbandictionary/README.md
plugins/urbandictionary/urbandictionary.js
plugins/urbandictionary/urbandictionary.json
plugins/warzone-stats/README.md
plugins/warzone-stats/warzone-stats.js
plugins/warzone-stats/warzone-stats.json

Plug-in 2.0.0 Rewrites: UrbanDictionary, Hydrate, Warzone

---

localization/de.json
localization/en.json
plugins/poll/README.md
plugins/poll/poll.js
plugins/poll/poll.json
plugins/poll/pollFunction.js

Here it is again.
Tested with fresh Bot and works for me
Changelog:
- Added commands to Readme
- Added German Translation

Re Pull: Poll System

---

localization/en.json
plugins/shout-out/shout-out.js

- original implement by @IceFlom
- usage:
!so default (username)
!so raid (username)

Plug-in (2.0.0): Integrate old 'Raid' command into 'Shout-out'plug-in

---

localization/en.json
plugins/giveaway/giveaway.js
plugins/giveaway/giveaway.json
plugins/join/join.js
plugins/join/join.json

Converted and Fixed Giveaway.
What would be great, if someone could add a Countdown timer so the Chat can see how much time is left

pull: Giveaway

---

plugins/giveaway/giveaway.json

Removed a comment in giveaway.json i forgot to remove.
Bye bye Comment

fix: Giveaway json

---

localization/en.json
plugins/raid/README.md
plugins/raid/raid.js
plugins/raid/raid.json
plugins/shout-out/shout-out.js

- since people find it awkward
This reverts commit 40e66b6799110a6f39c863b78849cbd27b5b84f8.
This reverts commit 5b60dc3b56926b78f35fe2f11c7734e630d86332.

Re-Separate 'Raid' and 'Shout-out'

---

processors/jsoncommands/jsoncommands.json

- this should be enabled by default for creators to use

jsoncommands: create, edit, delete enabled by default

---

plugins/alerts/alerts.js
plugins/alerts/alerts.json
plugins/alerts/spells.json

Fixed obs triggering even when not using obs.
Seperated the Spell Alert so if active the user can Test and Trigger Each Spell seperatly.
The spells.json will be loaded as the Alert is triggered what allows user to test the Alerts on the fly without restarting the Bot

pull: Fix and Sperated Spells

---

plugins/alerts/alerts.js
plugins/alerts/alerts.json
plugins/alerts/spells.json

Moved seperate spell activation to alerts.json

Update: Alert-System

---

processors/user-info/plugins/give/give.js

Removed bug where !give command will not add points tu the user

Fix: User-Info Give command

---

data/nodifications/nodifications.json
processors/nodifications/README.md
processors/nodifications/nodifications.js
processors/nodifications/nodifications.json

Added nodification processor
each Nodification has its own message Counter and its own Delay the user can set in data/nodifications/nodifications.json

pull: Nodification Processor

---

plugins/alerts/alerts.js
plugins/alerts/alerts.json

Bug Fix: Spell Alert

---

plugins/alerts/alerts.js
plugins/alerts/spells.json

Bug Fix:  Wrong naming for Spell Https
Added: httpMessage for Http Overlay

Bug Fix: Alert Http

---

localization/de.json
localization/en.json
localization/es.json
plugins/timed-messages/README.md
plugins/timed-messages/messages.txt
plugins/timed-messages/timed-messages.js
plugins/timed-messages/timed-messages.json

timed-messages plugin - automatically sends predefined messages to the chat.
I hope that fits with the pull request ;)

timed-messages plugin

---

plugins/alerts/alerts.js

Alert Spell Fix

---

plugins/alerts/alerts.js

This is to append to a file called latest-followers, keeping a list of each follower on a new line for future use, or record keeping.

Added Simple Function append2File

---

package.json
tools/changelog.js

how-to: node tools/changelog.js cli (latest commit) > changelog.md

[WIP] changelog: initial changelog creation script

---

localization/en.json
plugins/uptime/uptime.js
plugins/uptime/uptime.json

I forgot to commit these files to custom messages. sorry :c

add english text and fix replace customized text

---

localization/de.json
localization/en.json

fix for warzone-plugin output (anti-spam fix)

Fix for warzone-plugin output (anti-spam)

---

localization/de.json
localization/en.json

fix for the warzone-plugin output (anti-spam fix)

fix for the warzone-plugin output (anti-spam fix)

---

tools/windows-installer.ps1

Nothing real major, just a did a few quick fixes stopping it from running.

Fixed a Typo and Missed {

---

plugins/alerts/alerts.js

Modified the appending to prepend to file allowing most recent follower to be first.  Requires the Prepend dependency requested to add in previous pull request  206

Change of the append2File()

---

tools/windows-installer.ps1

Suggesting to change from NodeJS 12 to 14

Proposing change to use Node.JS Fermium for LTS

---

plugins/8ball/8ball.js
plugins/8ball/8ball.txt
plugins/8ball/README.md
plugins/flip/README.md
plugins/giveaway/README.md
plugins/giveaway/giveaway.js
plugins/join/README.md
plugins/say/README.md
plugins/timed-messages/README.md
processors/user-info/plugins/gamble/README.md
processors/user-info/plugins/gamble/gamble.js
processors/user-info/plugins/gamble/gamble.json

Updated a few READMEs, and added, "gamble" plugin under, "processor -> user-info". Added "!giveaway stop" function to the giveaway plugin. Altered 8ball.js to avoid returning undefined.

Praxem branch

---

processors/user-info/plugins/add/README.md
processors/user-info/plugins/add/add.js
processors/user-info/plugins/gamble/README.md
processors/user-info/plugins/gamble/gamble.js
processors/user-info/plugins/give/README.md
processors/user-info/plugins/give/give.js
processors/user-info/plugins/level/level.js
processors/user-info/plugins/points/points.js
processors/user-info/plugins/seen/seen.js
processors/user-info/plugins/vip/vip.js

Went through and corrected logic or refactored plugins under the user_info process

Complete user_info plugins touchup
